import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { colors, spacing } from '../../shared/theme';
import { useAuth } from '../auth/AuthProvider';
import { useTenant } from '../tenancy/TenantProvider';
import { canRegisterRemotePush, DEFAULT_NOTIFICATION_PREFERENCES, isExpoGo, loadNotificationPreferences, registerExpoPushToken, saveNotificationPreferences, type NotificationPreferences } from './notificationsApi';
export function NotificationPreferencesScreen({ onBack }: { onBack: () => void }) {
  const { session } = useAuth(); const { context } = useTenant(); const [value, setValue] = useState<NotificationPreferences>(DEFAULT_NOTIFICATION_PREFERENCES); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const mayEmail = context ? ['owner','admin','manager'].includes(context.membership.role) : false; const pushRegistrationAvailable = canRegisterRemotePush();
  useEffect(() => { if (!context || !session) return; void loadNotificationPreferences(context.tenant.id, session.user.id).then(setValue).catch(error => setMessage(error instanceof Error ? error.message : 'Unable to load preferences.')).finally(() => setLoading(false)); }, [context, session]);
  const update = (key: keyof NotificationPreferences, next: boolean) => setValue(current => ({ ...current, [key]: next }));
  const save = async () => { if (!context || !session || saving) return; setSaving(true); setMessage(null); try { if (value.pushEnabled && pushRegistrationAvailable) await registerExpoPushToken(context.tenant.id, session.user.id); await saveNotificationPreferences(context.tenant.id, session.user.id, value); setMessage(value.pushEnabled && isExpoGo() ? 'Preferences saved. Push registration is skipped in Expo Go; use a development build to test remote push.' : 'Notification preferences saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save preferences.'); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={styles.container}><Pressable onPress={onBack}><Text style={styles.link}>← Back</Text></Pressable><Text style={styles.title}>Notifications</Text><Text style={styles.body}>Choose which inventory events should reach this account. Location assignments still control which alerts you can receive.</Text>{loading ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : <>
    <Toggle label="Push notifications" detail={isExpoGo() ? 'Remote push requires a development or production build; Expo Go remains available for other testing.' : undefined} value={value.pushEnabled} onChange={next => update('pushEnabled', next)} /><Toggle label="Email alerts" detail={mayEmail ? 'Optional for owners, admins and managers' : 'Available to owners, admins and managers'} disabled={!mayEmail} value={mayEmail && value.emailEnabled} onChange={next => update('emailEnabled', next)} />
    <Text style={styles.section}>ALERT TYPES</Text><Toggle label="Low and out of stock" value={value.stockAlerts} onChange={next => update('stockAlerts', next)} /><Toggle label="Batch expiry" value={value.expiryAlerts} onChange={next => update('expiryAlerts', next)} /><Toggle label="Damaged goods" value={value.damageAlerts} onChange={next => update('damageAlerts', next)} /><Toggle label="Transfers awaiting receipt" value={value.transferAlerts} onChange={next => update('transferAlerts', next)} /><Toggle label="Offline sync failures" value={value.syncFailureAlerts} onChange={next => update('syncFailureAlerts', next)} />
    {message ? <Text style={message.includes('saved') ? styles.success : styles.error}>{message}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={styles.primary}><Text style={styles.primaryText}>{saving ? 'Saving…' : 'Save preferences'}</Text></Pressable></>}
  </ScrollView>;
}
function Toggle({ label, detail, value, disabled, onChange }: { label: string; detail?: string; value: boolean; disabled?: boolean; onChange: (value: boolean) => void }) { return <View style={[styles.toggle, disabled && styles.disabled]}><View style={styles.toggleText}><Text style={styles.toggleLabel}>{label}</Text>{detail ? <Text style={styles.detail}>{detail}</Text> : null}</View><Switch disabled={disabled} onValueChange={onChange} value={value} /></View>; }
const styles = StyleSheet.create({ container: { padding: spacing.xl }, link: { color: colors.primary, fontWeight: '700' }, title: { color: colors.text, fontSize: 32, fontWeight: '700', marginTop: spacing.lg }, body: { color: colors.textMuted, lineHeight: 20, marginTop: spacing.sm }, loader: { marginTop: spacing.xl }, section: { color: colors.primary, fontSize: 12, fontWeight: '700', letterSpacing: 1.2, marginTop: spacing.xl }, toggle: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.md }, disabled: { opacity: 0.55 }, toggleText: { flex: 1, paddingRight: spacing.md }, toggleLabel: { color: colors.text, fontWeight: '700' }, detail: { color: colors.textMuted, fontSize: 12, marginTop: spacing.xs }, primary: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, marginTop: spacing.xl, padding: spacing.md }, primaryText: { color: '#fff', fontWeight: '700' }, success: { color: colors.primary, marginTop: spacing.lg }, error: { color: '#B42318', marginTop: spacing.lg } });
