import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { operationLabel } from '../../core/offline/operation';
import { colors, spacing } from '../../shared/theme';
import { useOfflineSync } from './OfflineSyncProvider';
export function OfflineSyncScreen({ onBack }: { onBack: () => void }) {
  const { operations, syncing, retry, remove } = useOfflineSync();
  return <ScrollView contentContainerStyle={styles.container}><Pressable onPress={onBack}><Text style={styles.link}>← Back</Text></Pressable><Text style={styles.title}>Offline sync</Text><Text style={styles.body}>Operations are isolated to this signed-in user and business. Idempotency keys prevent replay from changing stock twice.</Text>
    {operations.length ? <Pressable disabled={syncing} onPress={() => void retry()} style={styles.primary}><Text style={styles.primaryText}>{syncing ? 'Syncing…' : 'Retry pending operations'}</Text></Pressable> : null}
    {!operations.length ? <Text style={styles.empty}>Everything is synchronized.</Text> : null}
    {operations.map(item => <View key={item.id} style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>{operationLabel(item.kind)}</Text><Text style={[styles.status, item.status === 'failed' && styles.failed]}>{item.status.toUpperCase()}</Text></View><Text style={styles.body}>Queued {new Date(item.createdAt).toLocaleString()} · Attempts {item.attempts}</Text>{item.lastError ? <Text style={styles.error}>{item.lastError}</Text> : null}{item.status === 'failed' ? <View style={styles.actions}><Pressable onPress={() => void retry(item.id)} style={styles.outline}><Text style={styles.outlineText}>Retry</Text></Pressable><Pressable onPress={() => void remove(item.id)}><Text style={styles.remove}>Remove</Text></Pressable></View> : null}</View>)}
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: spacing.xl }, link: { color: colors.primary, fontWeight: '700' }, title: { color: colors.text, fontSize: 32, fontWeight: '700', marginTop: spacing.lg }, body: { color: colors.textMuted, lineHeight: 20, marginTop: spacing.xs }, empty: { color: colors.textMuted, marginTop: spacing.xl }, primary: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, marginTop: spacing.lg, padding: spacing.md }, primaryText: { color: '#fff', fontWeight: '700' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, marginTop: spacing.md, padding: spacing.md }, row: { flexDirection: 'row', justifyContent: 'space-between' }, cardTitle: { color: colors.text, fontWeight: '700' }, status: { color: '#9A6700', fontSize: 11, fontWeight: '700' }, failed: { color: '#B42318' }, error: { color: '#B42318', marginTop: spacing.sm }, actions: { alignItems: 'center', flexDirection: 'row', gap: spacing.lg, marginTop: spacing.md }, outline: { borderColor: colors.primary, borderRadius: 10, borderWidth: 1, padding: spacing.sm }, outlineText: { color: colors.primary, fontWeight: '700' }, remove: { color: '#B42318', fontWeight: '700' } });
