import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { tenantSlug } from '../../core/tenancy/slug';
import { colors, spacing } from '../../shared/theme';
import { useTenant } from './TenantProvider';
export function TenantSelectionScreen({ onDone }: { onDone?: () => void }) {
  const { accesses, locations, context, choose, createTenant, error: loadError, reload } = useTenant();
  const [tenantId, setTenantId] = useState(context?.tenant.id ?? accesses[0]?.tenant.id ?? ''); const [locationId, setLocationId] = useState(context?.locationId ?? ''); const [name, setName] = useState(''); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
  const available = useMemo(() => locations.filter(location => location.tenantId === tenantId), [locations, tenantId]);
  async function selectContext() { const selected = locationId || available[0]?.id; if (!tenantId || !selected) return; setSubmitting(true); setError(null); try { await choose(tenantId, selected); onDone?.(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to select location.'); } finally { setSubmitting(false); } }
  async function createBusiness() { const slug = tenantSlug(name); if (!slug) return setError('Enter a valid business name.'); setSubmitting(true); setError(null); try { await createTenant(name, slug); setName(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create business.'); } finally { setSubmitting(false); } }
  return <ScrollView contentContainerStyle={styles.container}>
    <Text style={styles.eyebrow}>WORKSPACE</Text><Text style={styles.title}>{accesses.length ? 'Choose where you are working' : 'Create your first business'}</Text>
    {loadError ? <View><Text style={styles.error}>{loadError}</Text><Pressable onPress={() => void reload()}><Text style={styles.link}>Try again</Text></Pressable></View> : null}
    {accesses.map(access => <Pressable key={access.tenant.id} onPress={() => { setTenantId(access.tenant.id); setLocationId(''); }} style={[styles.option, tenantId === access.tenant.id && styles.selected]}><Text style={styles.optionTitle}>{access.tenant.name}</Text><Text style={styles.meta}>{access.membership.role} · {access.tenant.plan}</Text></Pressable>)}
    {available.length ? <Text style={styles.label}>Warehouse / location</Text> : null}
    {available.map(location => <Pressable key={location.id} onPress={() => setLocationId(location.id)} style={[styles.option, (locationId || available[0]?.id) === location.id && styles.selected]}><Text style={styles.optionTitle}>{location.name}</Text><Text style={styles.meta}>{location.code}</Text></Pressable>)}
    {accesses.length ? <Pressable disabled={submitting || !available.length} onPress={() => void selectContext()} style={[styles.button, (!available.length || submitting) && styles.disabled]}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Continue</Text>}</Pressable> : <View><Text style={styles.label}>Business name</Text><TextInput placeholder="Example Trading Ltd" value={name} onChangeText={setName} style={styles.input} /><Pressable disabled={submitting || !name.trim()} onPress={() => void createBusiness()} style={[styles.button, (submitting || !name.trim()) && styles.disabled]}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Create business</Text>}</Pressable></View>}
    {error ? <Text style={styles.error}>{error}</Text> : null}
  </ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: spacing.xl }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: '700', letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 30, fontWeight: '700', marginBottom: spacing.lg, marginTop: spacing.sm }, option: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, marginBottom: spacing.sm, padding: spacing.md }, selected: { borderColor: colors.primary, borderWidth: 2 }, optionTitle: { color: colors.text, fontSize: 16, fontWeight: '700' }, meta: { color: colors.textMuted, marginTop: spacing.xs }, label: { color: colors.text, fontWeight: '700', marginBottom: spacing.sm, marginTop: spacing.md }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, fontSize: 16, padding: spacing.md }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, justifyContent: 'center', marginTop: spacing.lg, minHeight: 52 }, buttonText: { color: '#fff', fontWeight: '700' }, disabled: { opacity: 0.5 }, error: { color: '#B42318', marginTop: spacing.md }, link: { color: colors.primary, fontWeight: '700', marginTop: spacing.sm } });
