import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, spacing } from '../../shared/theme';
import { useTenant } from '../tenancy/TenantProvider';
import { listProducts, type ProductInventory } from './inventoryApi';

export function InventoryScreen({ onBack, onProduct, onScan }: { onBack: () => void; onProduct: (id: string) => void; onScan: () => void }) {
  const { context, locations } = useTenant(); const [search, setSearch] = useState(''); const [products, setProducts] = useState<ProductInventory[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const location = locations.find(item => item.id === context?.locationId);
  const load = useCallback(async (query = search) => { if (!context) return; setError(null); try { setProducts(await listProducts(context.tenant.id, context.locationId, query)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load products.'); } finally { setLoading(false); setRefreshing(false); } }, [context, search]);
  useEffect(() => { const timer = setTimeout(() => void load(search), 300); return () => clearTimeout(timer); }, [load, search]);
  return <View style={styles.screen}>
    <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.link}>‹ Home</Text></Pressable><View><Text style={styles.title}>Inventory</Text><Text style={styles.subtitle}>{location?.name}</Text></View><Pressable onPress={onScan} style={styles.scan}><Text style={styles.scanText}>Scan</Text></Pressable></View>
    <TextInput autoCapitalize="none" placeholder="Search name or barcode" value={search} onChangeText={setSearch} style={styles.input} />
    {loading ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}
    <FlatList data={products} keyExtractor={item => item.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />} contentContainerStyle={products.length ? styles.list : styles.emptyList}
      ListEmptyComponent={!loading ? <Text style={styles.empty}>{search ? 'No matching products.' : 'No active products.'}</Text> : null}
      renderItem={({ item }) => <Pressable onPress={() => onProduct(item.id)} style={styles.row}><View style={styles.rowMain}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.barcode ?? 'No barcode'}{item.category ? ` · ${item.category}` : ''}</Text></View><View style={styles.quantity}><Text style={styles.quantityValue}>{item.locationQuantity}</Text><Text style={styles.quantityLabel}>units</Text></View></Pressable>} />
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: spacing.lg }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.md }, link: { color: colors.primary, fontWeight: '700' }, title: { color: colors.text, fontSize: 24, fontWeight: '700', textAlign: 'center' }, subtitle: { color: colors.textMuted, fontSize: 12, textAlign: 'center' }, scan: { backgroundColor: colors.primary, borderRadius: 10, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, scanText: { color: '#fff', fontWeight: '700' }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, fontSize: 16, padding: spacing.md }, loader: { marginTop: spacing.lg }, error: { color: '#B42318', marginTop: spacing.md }, list: { paddingBottom: spacing.xl, paddingTop: spacing.md }, emptyList: { flexGrow: 1, justifyContent: 'center' }, empty: { color: colors.textMuted, textAlign: 'center' }, row: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, flexDirection: 'row', marginBottom: spacing.sm, padding: spacing.md }, rowMain: { flex: 1 }, name: { color: colors.text, fontSize: 16, fontWeight: '700' }, meta: { color: colors.textMuted, fontSize: 12, marginTop: spacing.xs }, quantity: { alignItems: 'center', backgroundColor: colors.background, borderRadius: 10, minWidth: 62, padding: spacing.sm }, quantityValue: { color: colors.primary, fontSize: 20, fontWeight: '700' }, quantityLabel: { color: colors.textMuted, fontSize: 11 } });
