import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { canManageInventory } from '../../core/tenancy/permissions';
import { colors, spacing } from '../../shared/theme';
import { useTenant } from '../tenancy/TenantProvider';
import { loadProductDetail, type ProductDetail } from './inventoryApi';

export function ProductDetailScreen({ productId, refreshKey, onBack, onMove, onTransfer }: { productId: string; refreshKey: number; onBack: () => void; onMove: (type: 'in' | 'out') => void; onTransfer: (batchId: string) => void }) {
  const { context, locations } = useTenant(); const [product, setProduct] = useState<ProductDetail | null>(null); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const location = locations.find(item => item.id === context?.locationId);
  const load = useCallback(async () => { if (!context) return; setError(null); try { setProduct(await loadProductDetail(context.tenant.id, context.locationId, productId)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load product.'); } finally { setRefreshing(false); } }, [context, productId]);
  useEffect(() => { setProduct(null); void load(); }, [load, refreshKey]);
  if (!context) return null;
  return <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}><Pressable onPress={onBack}><Text style={styles.link}>‹ Inventory</Text></Pressable>
    {!product && !error ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}
    {product ? <><Text style={styles.title}>{product.name}</Text><Text style={styles.meta}>{product.barcode ?? 'No barcode'}{product.category ? ` · ${product.category}` : ''}</Text>
      <View style={styles.stockCard}><View><Text style={styles.stockLabel}>Stock at {location?.name}</Text><Text style={styles.stockValue}>{product.locationQuantity}</Text></View><View><Text style={styles.stockLabel}>Tenant total incl. transit</Text><Text style={styles.totalValue}>{product.totalQuantity}</Text></View></View>
      <Text style={styles.price}>GH₵ {product.price.toFixed(2)}</Text>{product.description ? <Text style={styles.description}>{product.description}</Text> : null}
      {canManageInventory(context.membership.role) ? <View style={styles.actions}><Pressable onPress={() => onMove('in')} style={styles.primary}><Text style={styles.primaryText}>Stock in</Text></Pressable><Pressable onPress={() => onMove('out')} style={styles.outline}><Text style={styles.outlineText}>Stock out</Text></Pressable></View> : <Text style={styles.readOnly}>Your role has read-only inventory access.</Text>}
      <Text style={styles.section}>Batches at {location?.name}</Text>{product.batches.length ? product.batches.map(batch => <View key={batch.id} style={styles.batch}><View style={styles.transactionMain}><Text style={styles.transactionType}>{batch.batchNumber}</Text><Text style={styles.transactionMeta}>{batch.expiryDate ? `Expires ${formatDate(batch.expiryDate)}` : 'Expiry not tracked (legacy stock)'}</Text>{canManageInventory(context.membership.role) ? <Pressable onPress={() => onTransfer(batch.id)}><Text style={styles.transferLink}>Transfer this batch</Text></Pressable> : null}</View><View><Text style={styles.batchQuantity}>{batch.quantity}</Text><Text style={[styles.batchStatus, (batch.expiryStatus === 'expired' || batch.expiryStatus === 'critical') && styles.negative]}>{formatBatchStatus(batch.expiryStatus)}</Text></View></View>) : <Text style={styles.empty}>No stock batches at this location.</Text>}
      <Text style={styles.section}>Recent activity at {location?.name}</Text>{product.transactions.length ? product.transactions.map(item => <View key={item.id} style={styles.transaction}><View style={styles.transactionMain}><Text style={styles.transactionType}>{formatType(item.type)}</Text><Text style={styles.transactionMeta}>{new Date(item.createdAt).toLocaleString()}{item.remarks ? ` · ${item.remarks}` : ''}</Text></View><View><Text style={[styles.delta, item.quantity < 0 ? styles.negative : styles.positive]}>{item.quantity > 0 ? '+' : ''}{item.quantity}</Text><Text style={styles.balance}>{item.newStock ?? '—'} after</Text></View></View>) : <Text style={styles.empty}>No transactions at this location yet.</Text>}
    </> : null}</ScrollView>;
}
function formatType(type: string) { return type.charAt(0) + type.slice(1).toLowerCase(); }
function formatDate(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString(); }
function formatBatchStatus(status: string) { return status === 'untracked' ? 'Untracked' : status.charAt(0).toUpperCase() + status.slice(1); }
const styles = StyleSheet.create({ container: { padding: spacing.xl }, link: { color: colors.primary, fontWeight: '700' }, loader: { marginTop: spacing.xl }, error: { color: '#B42318', marginTop: spacing.lg }, title: { color: colors.text, fontSize: 30, fontWeight: '700', marginTop: spacing.xl }, meta: { color: colors.textMuted, marginTop: spacing.sm }, stockCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xl, padding: spacing.lg }, stockLabel: { color: colors.textMuted, fontSize: 12 }, stockValue: { color: colors.primary, fontSize: 36, fontWeight: '700', marginTop: spacing.xs }, totalValue: { color: colors.text, fontSize: 30, fontWeight: '700', marginTop: spacing.xs, textAlign: 'right' }, price: { color: colors.text, fontSize: 20, fontWeight: '700', marginTop: spacing.lg }, description: { color: colors.textMuted, lineHeight: 22, marginTop: spacing.sm }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xl }, primary: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, flex: 1, padding: spacing.md }, primaryText: { color: '#fff', fontWeight: '700' }, outline: { alignItems: 'center', borderColor: colors.primary, borderRadius: 12, borderWidth: 1, flex: 1, padding: spacing.md }, outlineText: { color: colors.primary, fontWeight: '700' }, readOnly: { color: colors.textMuted, marginTop: spacing.xl }, section: { color: colors.text, fontSize: 18, fontWeight: '700', marginTop: spacing.xl }, batch: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', paddingVertical: spacing.md }, batchQuantity: { color: colors.text, fontSize: 18, fontWeight: '700', textAlign: 'right' }, batchStatus: { color: colors.textMuted, fontSize: 11, textAlign: 'right' }, transferLink: { color: colors.primary, fontSize: 12, fontWeight: '700', marginTop: spacing.sm }, transaction: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', paddingVertical: spacing.md }, transactionMain: { flex: 1 }, transactionType: { color: colors.text, fontWeight: '700' }, transactionMeta: { color: colors.textMuted, fontSize: 12, marginTop: spacing.xs }, delta: { fontSize: 18, fontWeight: '700', textAlign: 'right' }, positive: { color: colors.primary }, negative: { color: '#B42318' }, balance: { color: colors.textMuted, fontSize: 11 }, empty: { color: colors.textMuted, marginTop: spacing.md } });
